### ISSUE TITLE
Add GTIN field

### ISSUE THREAD

**Issue by vseager** [outeredge/magento-structured-data-module#35]
* Add `gtin` to product schema
* Add config option to allow user to select the attribute used for `gtin`

**Comment by AlohaJeff** [comment]
This would be a very much appreciated new feature!

**Comment by davidwindell** [comment]
@AlohaJeff we've got this one schedule in our sprints towards the end of January, PR's welcome in the meantime.

**Comment by davidwindell** [comment]
@AlohaJeff this has now been added to the module

**Comment by AlohaJeff** [comment]
@davidwindell Awesome - Thank you!
