### ISSUE TITLE
Product review schema missing "itemReviewed"

### ISSUE THREAD

**Issue by vseager** [outeredge/magento-structured-data-module#37]
Product review schema missing "itemReviewed":

![screenshot-search google com-2022 12 06-15_15_48](https://user-images.githubusercontent.com/2035088/205950736-9c1ec495-e2a6-4da3-a90b-77a2ecf3c8f9.png)

**Comment by davidwindell** [comment]
Suggest we add an after plugin on https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/app/code/Magento/Review/Block/Product/ReviewRenderer.php#L101 that uses dom manipulation to delete the inline schema

**Comment by LKoomenKeesing** [comment]
Why has this been closed like this?
I don't see how your comment is related? I like the module, but the reviews are not valid according to the https://search.google.com/test/rich-results tester.
