### ISSUE TITLE
StripReviewSummary utf-8 ecoding

### ISSUE THREAD

**Issue by atolodas** [outeredge/magento-structured-data-module#43]
Change:
OuterEdge\StructuredData\Plugin\StripReviewSummary line 16 $dom->loadHTML($result); to $dom->loadHTML(mb_convert_encoding($result, 'HTML-ENTITIES', 'UTF-8'));

OuterEdge\StructuredData\Block\Cms line 146 $doc->loadHtml($content); $doc->loadHTML(mb_convert_encoding($content, 'HTML-ENTITIES', 'UTF-8'));

**Comment by davidwindell** [comment]
@atolodas thanks for your contribution, can you give some background to this request?

**Comment by davidwindell** [comment]
Issue has gone stale, closing
