### ISSUE TITLE
Array in application/ld+json

### ISSUE THREAD

**Issue by sebfie** [outeredge/magento-structured-data-module#53]
Hello,

I can see here : https://github.com/outeredge/magento-structured-data-module/blob/master/view/frontend/templates/jsonld.phtml#L4 you are using an array and I think it should be a hash directly because if generates an error on Safari : 

undefined is not an object (evaluating 'r["@context"].toLowerCase')

Thank you !

**Comment by davidwindell** [comment]
Thanks @sebfie, fixed in v4.0.3
