### ISSUE TITLE
Cannot uninstall module

### ISSUE THREAD

**Issue by hirosalc** [outeredge/magento-structured-data-module#60]
Hi,

I have tried uninstalling this module as it seems it's causing that anytime I update and save changes in a product, it loads for a minute or more and causes server timeouts.

This is the error I get after uninstalling it:
<img width="1597" alt="Screenshot 2023-11-29 at 9 29 49 AM" src="https://github.com/outeredge/magento-structured-data-module/assets/62911018/34fe6867-96ee-42a3-8d78-817bbdd9dbc6">

Please help

**Comment by davidwindell** [comment]
@hirosalc are you sure that's our module as we don't have any Observers that would affect admin actions?

Regarding the removal error, you need to use composer to remove the module with `composer remove` and not just delete it otherwise you'll get autoload errors.
