### ISSUE TITLE
Indexers dont work (stuck) on Magento 2.4.6-p3

### ISSUE THREAD

**Issue by aurel5542** [outeredge/magento-structured-data-module#64]
Hello,
I installed on Magento 2.4.6-p3. It works fine but the indexers (System -> Index Management) for Category Products and Product Categories stop working. First they were stuck in "working" after forced reindex they are stuck in "processing". I tried to turn of the Categorys feature in the module settings but still the same. After disabling the extension everything works fine.

Other bugs:
- Also my breadcrums are moved from center div to left
- Price is correct but snippet for Tax is false "including tax: false". I have the price including tax and excluding tax on the website but the snipped should give including tax: true

Best regards

**Comment by vseager** [comment]
@aurel5542 thanks for the feedback

> Also my breadcrums are moved from center div to left

This is not a bug, you probably have some theme customisations that you will need to carry over to the new breadcrumb template:  
https://github.com/outeredge/magento-structured-data-module/blob/master/view/frontend/templates/html/breadcrumbs.phtml

> Price is correct but snippet for Tax is false "including tax: false". I have the price including tax and excluding tax on the website but the snipped should give including tax: true

Thanks for bringing this to our attention, we have resolved this issue now and you can benefit from the fix in the latest version 4.0.9

**Comment by vseager** [comment]
@aurel5542 Sorry I forgot to respond to your query about indexers. This extension is purely frontend and doesn't interfere with the indexers or any backend functionality. It very unlikely that our module will be causing this issue.

The module is used on all of our own customer's 2.4.6-p3 sites with no indexing issues and is used by thousands of others with no reported indexing issue either.

If you are installing via composer you may updating other modules at the same time which could be causing the issue.

If you believe that this is not the case and you can provide error logs suggesting that the indexing issue relates our module please send us the logs and we will be happy to resolve the issue.
